"""Add photo storage to Inspection table

Revision ID: 5a52edd2ec12
Revises: 
Create Date: 2025-11-11 19:51:14.816499

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5a52edd2ec12'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('inspection', schema=None) as batch_op:
        batch_op.add_column(sa.Column('photo_data', sa.LargeBinary(), nullable=True))
        batch_op.add_column(sa.Column('photo_filename', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('photo_uploaded_at', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('inspection', schema=None) as batch_op:
        batch_op.drop_column('photo_uploaded_at')
        batch_op.drop_column('photo_filename')
        batch_op.drop_column('photo_data')

    # ### end Alembic commands ###
