"""説明文：何を変更したか

Revision ID: 9a367de1026e
Revises: e50676c0844a
Create Date: 2025-12-12 01:08:30.830542

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9a367de1026e'
down_revision = 'e50676c0844a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('daily_reports',
    sa.Column('daily_report_id', sa.Integer(), nullable=False),
    sa.Column('park_id', sa.Integer(), nullable=False),
    sa.Column('employee_id', sa.Integer(), nullable=False),
    sa.Column('report_date', sa.DateTime(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['employee_id'], ['users.employee_id'], ),
    sa.ForeignKeyConstraint(['park_id'], ['parks.park_id'], ),
    sa.PrimaryKeyConstraint('daily_report_id')
    )
    op.create_table('daily_report_detail',
    sa.Column('detail_id', sa.Integer(), nullable=False),
    sa.Column('daily_report_id', sa.Integer(), nullable=False),
    sa.Column('equipment_id', sa.Integer(), nullable=False),
    sa.Column('condition', sa.Enum('NORMAL', 'RUST', 'CRACK', 'WEAR', 'LOOSE', 'DEFORM', name='conditionenum'), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('remarks', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['daily_report_id'], ['daily_reports.daily_report_id'], ),
    sa.ForeignKeyConstraint(['equipment_id'], ['equipments.equipment_id'], ),
    sa.PrimaryKeyConstraint('detail_id'),
    sa.UniqueConstraint('daily_report_id', 'equipment_id', name='unique_daily_report_equipment')
    )
    op.create_table('daily_report_photo',
    sa.Column('photo_id', sa.Integer(), nullable=False),
    sa.Column('daily_report_id', sa.Integer(), nullable=False),
    sa.Column('detail_id', sa.Integer(), nullable=True),
    sa.Column('filename', sa.String(length=255), nullable=False),
    sa.Column('file_path', sa.String(length=500), nullable=True),
    sa.Column('storage_url', sa.String(length=500), nullable=True),
    sa.Column('file_size', sa.Integer(), nullable=True),
    sa.Column('mime_type', sa.String(length=50), nullable=True),
    sa.Column('photo_data', sa.LargeBinary(), nullable=True),
    sa.Column('uploaded_at', sa.DateTime(), nullable=True),
    sa.Column('uploaded_by', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['daily_report_id'], ['daily_reports.daily_report_id'], ),
    sa.ForeignKeyConstraint(['detail_id'], ['daily_report_detail.detail_id'], ),
    sa.ForeignKeyConstraint(['uploaded_by'], ['users.employee_id'], ),
    sa.PrimaryKeyConstraint('photo_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('daily_report_photo')
    op.drop_table('daily_report_detail')
    op.drop_table('daily_reports')
    # ### end Alembic commands ###
