"""Add inspection_detail and inspection_photo tables

Revision ID: e50676c0844a
Revises: 
Create Date: 2025-12-03 07:45:39.149737

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'e50676c0844a'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('inspection_detail',
    sa.Column('detail_id', sa.Integer(), nullable=False),
    sa.Column('inspection_id', sa.Integer(), nullable=False),
    sa.Column('part', sa.Enum('CHAIN', 'JOINT', 'POLE', 'SEAT', name='inspectionpartenum'), nullable=False),
    sa.Column('condition', sa.Enum('NORMAL', 'RUST', 'CRACK', 'WEAR', 'LOOSE', 'DEFORM', name='conditionenum'), nullable=True),
    sa.Column('grade', sa.Enum('A', 'B', 'C', 'D', name='gradeenum'), nullable=True),
    sa.Column('is_ai_predicted', sa.Boolean(), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('ai_raw_result', sa.Text(), nullable=True),
    sa.Column('remarks', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['inspection_id'], ['inspection.inspection_id'], ),
    sa.PrimaryKeyConstraint('detail_id'),
    sa.UniqueConstraint('inspection_id', 'part', name='unique_inspection_part')
    )
    op.create_table('inspection_photo',
    sa.Column('photo_id', sa.Integer(), nullable=False),
    sa.Column('inspection_id', sa.Integer(), nullable=False),
    sa.Column('detail_id', sa.Integer(), nullable=True),
    sa.Column('filename', sa.String(length=255), nullable=False),
    sa.Column('file_path', sa.String(length=500), nullable=True),
    sa.Column('storage_url', sa.String(length=500), nullable=True),
    sa.Column('file_size', sa.Integer(), nullable=True),
    sa.Column('mime_type', sa.String(length=50), nullable=True),
    sa.Column('photo_data', sa.LargeBinary(), nullable=True),
    sa.Column('uploaded_at', sa.DateTime(), nullable=True),
    sa.Column('uploaded_by', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['detail_id'], ['inspection_detail.detail_id'], ),
    sa.ForeignKeyConstraint(['inspection_id'], ['inspection.inspection_id'], ),
    sa.ForeignKeyConstraint(['uploaded_by'], ['users.employee_id'], ),
    sa.PrimaryKeyConstraint('photo_id')
    )
    op.drop_table('inspection_users')
    with op.batch_alter_table('inspection', schema=None) as batch_op:
        batch_op.add_column(sa.Column('photography_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('inspection_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('photographer_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('inspector_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('overall_grade', sa.Enum('A', 'B', 'C', 'D', name='gradeenum'), nullable=True))
        batch_op.add_column(sa.Column('actions_taken', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('response_plan', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('planned_response_date', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('created_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('updated_at', sa.DateTime(), nullable=True))
        batch_op.alter_column('inspection_date',
               existing_type=mysql.DATETIME(),
               nullable=False)
        batch_op.create_foreign_key(None, 'users', ['photographer_id'], ['employee_id'])
        batch_op.create_foreign_key(None, 'users', ['inspector_id'], ['employee_id'])
        batch_op.drop_column('overall_result')
        batch_op.drop_column('image_url')
        batch_op.drop_column('photo_data')
        batch_op.drop_column('photo_filename')
        batch_op.drop_column('photo_uploaded_at')
        batch_op.drop_column('result')
        batch_op.drop_column('ai_result')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('inspection', schema=None) as batch_op:
        batch_op.add_column(sa.Column('ai_result', mysql.TEXT(), nullable=True))
        batch_op.add_column(sa.Column('result', mysql.ENUM('NO_ISSUE', 'OBSERVATION', 'REPAIR_NEEDED'), nullable=True))
        batch_op.add_column(sa.Column('photo_uploaded_at', mysql.DATETIME(), nullable=True))
        batch_op.add_column(sa.Column('photo_filename', mysql.VARCHAR(length=255), nullable=True))
        batch_op.add_column(sa.Column('photo_data', sa.BLOB(), nullable=True))
        batch_op.add_column(sa.Column('image_url', mysql.VARCHAR(length=500), nullable=True))
        batch_op.add_column(sa.Column('overall_result', mysql.ENUM('A', 'B', 'C', 'D'), nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.alter_column('inspection_date',
               existing_type=mysql.DATETIME(),
               nullable=True)
        batch_op.drop_column('updated_at')
        batch_op.drop_column('created_at')
        batch_op.drop_column('planned_response_date')
        batch_op.drop_column('response_plan')
        batch_op.drop_column('actions_taken')
        batch_op.drop_column('overall_grade')
        batch_op.drop_column('inspector_id')
        batch_op.drop_column('photographer_id')
        batch_op.drop_column('inspection_at')
        batch_op.drop_column('photography_at')

    op.create_table('inspection_users',
    sa.Column('inspection_user_id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('inspection_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('employee_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('assigned_date', mysql.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['employee_id'], ['users.employee_id'], name=op.f('inspection_users_ibfk_2')),
    sa.ForeignKeyConstraint(['inspection_id'], ['inspection.inspection_id'], name=op.f('inspection_users_ibfk_1')),
    sa.PrimaryKeyConstraint('inspection_user_id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.drop_table('inspection_photo')
    op.drop_table('inspection_detail')
    # ### end Alembic commands ###
